spring.application.name=catalog-service
server.address=127.0.0.1
server.port=8181
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
spring.mvc.problemdetails.enabled=true
server.error.include-message=never
server.error.include-stacktrace=never
pedidos.security.issuer=${JWT_ISSUER}
pedidos.security.audience=${JWT_AUDIENCE}
pedidos.security.jwks=${JWT_JWKS_URI}
spring.datasource.url=${CATALOG_DB_URL}
spring.datasource.username=${CATALOG_DB_USER}
spring.datasource.password=${CATALOG_DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.flyway.url=${spring.datasource.url}
spring.flyway.user=${CATALOG_MIGRATION_USER}
spring.flyway.password=${CATALOG_MIGRATION_PASSWORD}
pedidos.security.tenant=${JWT_TENANT_ID}
pedidos.security.client=${JWT_CLIENT_ID}
