spring.application.name=bff
server.address=127.0.0.1
server.port=8180
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
spring.mvc.problemdetails.enabled=true
server.error.include-message=never
server.error.include-stacktrace=never
pedidos.security.issuer=${JWT_ISSUER}
pedidos.security.audience=${JWT_AUDIENCE}
pedidos.security.jwks=${JWT_JWKS_URI}
pedidos.catalog-url=${CATALOG_URL:http://127.0.0.1:8181}
pedidos.orders-url=${ORDERS_URL:http://127.0.0.1:8182}
pedidos.security.tenant=${JWT_TENANT_ID}
pedidos.security.client=${JWT_CLIENT_ID}
